version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    restart: unless-stopped
